remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Enabling the Geospatial Turn in the Social Sciences through Cyberinfrastructure Training]
description: [A set of curriculum modules and hands-on activities to train social scientists in the use of geospatial datasets and GIS libraries]
